version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5431:5432

networks:
  default:
    external:
      name: healthcheck-network