version: '3.7'

services:
  front:
    build:
      dockerfile: ./Dockerfile
      context: ./
    command: /app/start.sh
    ports:
      - 8090:8090

networks:
  default:
    external:
      name: healthcheck-network